
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/' #change it according to your repository name



# Profile information
yourname: Aloysius Tatus Kristanto  ## put your name
title: 'Information System'  ## your title
location: Madiun,East Java


## Social Profiles
facebook: http://www.facebook.com/Aloysius.Tatus.Kristanto  ## your facebook account url
twitter: http://www.twitter.com/aloysius_tatus  ## your twitter account url
linkedin: http://www.linkedin.com/in/aloysius-tatus-kristanto-658a88b5/  ## your linkedin account url
dribbble: https://open.spotify.com/user/21rdwbpxyv5qu4rt46mcgzjsq?si=mr9dBvR_QyWNwtS07d-tEg  ## you spotify account url
foursquare: http://www.instagram.com/aloysius_tatus  ## your Instagram account url



# Update all the sections by editing the files inside _includes folder.
